// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpzn4hFnD0GbvwwY5Pxcer4IPrIYfHKI0',
    appId: '1:590268875018:web:6d31ce3e61440531dbbaf3',
    messagingSenderId: '590268875018',
    projectId: 'foodie-app-36e2a',
    authDomain: 'foodie-app-36e2a.firebaseapp.com',
    databaseURL: 'https://foodie-app-36e2a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodie-app-36e2a.appspot.com',
    measurementId: 'G-6DLW8TQ0WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuSH_Vt9Yq32u_HmHFLdlhmIQ5yXKz2ho',
    appId: '1:590268875018:android:da150551530be7f1dbbaf3',
    messagingSenderId: '590268875018',
    projectId: 'foodie-app-36e2a',
    databaseURL: 'https://foodie-app-36e2a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodie-app-36e2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdgdNlkCEnJx3sBoDWi0tRDwi_uFp1CpM',
    appId: '1:590268875018:ios:25cc27efffea55aedbbaf3',
    messagingSenderId: '590268875018',
    projectId: 'foodie-app-36e2a',
    databaseURL: 'https://foodie-app-36e2a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodie-app-36e2a.appspot.com',
    iosClientId: '590268875018-4r1rjfot74jvok78lpn2230r475448mf.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdgdNlkCEnJx3sBoDWi0tRDwi_uFp1CpM',
    appId: '1:590268875018:ios:931892a66469a225dbbaf3',
    messagingSenderId: '590268875018',
    projectId: 'foodie-app-36e2a',
    databaseURL: 'https://foodie-app-36e2a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodie-app-36e2a.appspot.com',
    iosClientId: '590268875018-8l863v2mhhhkft4f0344fuad9lltsos5.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp2.RunnerTests',
  );
}
